Repository Ostorlab/KB, pull requests merged in 2025-03, with the labels that each got.

#227 feature: Add semantic-pull-request GitHub Action `KB`
  .github/workflows/lint-pr.yml
Labels: fixit!, action

#230 fix: correct privacy issue value
  MOBILE_CLIENT/ANDROID/_INFO/APK_DYNAMIC_HASH/meta.json
  MOBILE_CLIENT/ANDROID/_LOW/APK_TASK_HIJACKING/meta.json
  MOBILE_CLIENT/ANDROID/_LOW/APK_USES_CLEAR_TEXT_TRAFFIC/meta.json
  MOBILE_CLIENT/COMMON/_HIGH/INSECURE_VIRUSTOTAL_SCAN/meta.json
  MOBILE_CLIENT/COMMON/_HIGH/TAPJACKING_VULNERABILITY/meta.json
  MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_CIPHER_ALGO/meta.json
  MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_CIPHER_MODE/meta.json
  MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_IV/meta.json
  MOBILE_CLIENT/COMMON/_LOW/INSECURE_RANDOM_SEED/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/BIOMETRIC_AUTHENTICATION_BYPASS/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/CRYPTO_INSECURE_CIPHER_KEY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_DYNAMICALLY_LINKED_LIBRARY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_PASSWORD_STORAGE/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_PERMISSION_FILESYSTEM/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_STORAGE/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/LEAKING_CREDENTIALS_LOGS/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/LEAKING_CREDENTIALS_REQUEST/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/OAUTH_SCHEME_ACCOUNT_TAKEOVER/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/SQL_INJECTION/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/WEAK_HASHING_ALGO/meta.json
  MOBILE_CLIENT/COMMON/_POTENTIALLY/SECRETS_REVIEW/meta.json
  MOBILE_CLIENT/IOS/_LOW/PLIST_INSECURE_UI_FILE_SHARING/meta.json
  MOBILE_CLIENT/IOS/_LOW/UNSAFE_KEYCHAIN_ACCESSIBILITY/meta.json
  MOBILE_CLIENT/IOS/_MEDIUM/IPA_INSECURE_TAP/meta.json
  WEB_SERVICE/DNS/_MEDIUM/SUBDOMAIN_TAKEOVER/meta.json
  WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/meta.json
  WEB_SERVICE/WEB/_CRITICAL/WEB_SQL_INJECTION/meta.json
  WEB_SERVICE/WEB/_CRITICAL/WEB_XPATH_INJECTION/meta.json
  WEB_SERVICE/WEB/_HARDENING/WEB_COOKIE_MISSING_SECURITY_FLAGS/meta.json
  WEB_SERVICE/WEB/_HIGH/CRLF_INJECTION/meta.json
  WEB_SERVICE/WEB/_HIGH/INSECURE_AUTHORIZATION_RESTRICTION/meta.json
  WEB_SERVICE/WEB/_HIGH/TLS_HEARTBLEED/meta.json
  WEB_SERVICE/WEB/_HIGH/TLS_SELFSIGNED/meta.json
  WEB_SERVICE/WEB/_HIGH/WEB_XML_INJECTION/meta.json
  WEB_SERVICE/WEB/_INFO/TLS_SERVER_SCAN/meta.json
  WEB_SERVICE/WEB/_LOW/USER_ENUMERATION/meta.json
  WEB_SERVICE/WEB/_MEDIUM/INSECURE_TLS_VALIDATION/meta.json
  WEB_SERVICE/WEB/_MEDIUM/TLS_DEPRECATED_PROTOCOL/meta.json
  WEB_SERVICE/WEB/_MEDIUM/TLS_HTTP/meta.json
  WEB_SERVICE/WEB/_MEDIUM/TLS_INSECURE_CIPHER/meta.json
  WEB_SERVICE/WEB/_MEDIUM/TLS_INVALIDHOSTNAME/meta.json
  WEB_SERVICE/WEB/_POTENTIALLY/SECRETS_NETWORK_REVIEW/meta.json
  WEB_SERVICE/WEB/_SECURE/TLS_INVALIDHOSTNAME_SECURE/meta.json
  WEB_SERVICE/WEB/_SECURE/UNIQUE_USER_IDENTIFICATION/meta.json
Labels: fixit!

#233 feature: add privacy cnil standards
  MOBILE_CLIENT/ANDROID/_HARDENING/APK_INSECURE_NETWORK_SECURITY_CONFIG/meta.json
  MOBILE_CLIENT/ANDROID/_HIGH/APK_NOTIFICATION_SPOOFING/meta.json
  MOBILE_CLIENT/ANDROID/_MEDIUM/INSECURE_API_BLUETOOTH/meta.json
  MOBILE_CLIENT/ANDROID/_MEDIUM/INSECURE_PERMISSION_SHARED_PREFERENCES/meta.json
  MOBILE_CLIENT/COMMON/_HIGH/WIFI_API_PII/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/COLLECTION_OF_USERS_CRASH_LOGS_WITHOUT_CONSENT/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/COLLECTION_OF_USERS_PURCHASE_HISTORY_WITHOUT_CONSENT/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/COLLECTION_OF_USERS_TEXT_MESSAGES_WITHOUT_CONSENT/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/CONTACTS_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/CONTACT_INFORMATION_MISSING_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/DEVICE_ID_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/HEALTH_AND_BIOMETRIC_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/INAPP_SEARCH_HISTORY_COLLECTION_WITHOUT_CONSENT/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/LEAKING_PERSONAL_INFORMATION/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_APPROXIMATE_LOCATION_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_CONTACT_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_DEVICE_OR_OTHER_IDS_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_EMAIL_ADDRESS_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_EMAIL_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_HEALTH_INFO_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_INSTALLED_APPS_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_PHONE_NUMBER_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_PHOTO_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_PRECISE_LOCATION_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_USER_FILES_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_VIDEO_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_VOICE_OR_SOUND_RECORDING_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_DECLARATION_OF_WEB_BROWSING_HISTORY_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_GDPR_RIGHTS_REFERENCE_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_LEGAL_BASIS_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_MENTION_OF_USERS_RIGHT_TO_KNOW_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_MENTION_OF_USER_DATA_ACCESS_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_MENTION_OF_USER_DATA_CORRECTION_RIGHTS_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_MENTION_OF_USER_DATA_DELETION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_OPTOUT_INFORMATION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_PRIVACY_POLICY_DISCLOSURE_FOR_CALENDAR_EVENTS_COLLECTION/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_PRIVACY_POLICY_DISCLOSURE_FOR_FITNESS_INFO_COLLECTION/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_PRIVACY_POLICY_LINK/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/MISSING_THIRDPARTY_SHARING_INFORMATION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/PHONE_NUMBER_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/PII_CATEGORIES_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/PII_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/PRECISE_LOCATION_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/PRIVACY_POLICY_CCPA_RIGHTS_REFERENCE_MISSING/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/PRIVACY_POLICY_DATA_RETENTION_DESCRIPTION/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/PRIVACY_POLICY_PERSONAL_DATA_CATEGORIES_DISCLOSURE/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/SENSITIVE_INFORMATION_DATA_TYPE_DECLARATION_MISSING/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/TEXT_MESSAGES_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/USER_ACCOUNT_INFO_DATA_TYPE_DECLARATION_MISMATCH/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/USER_ID_COLLECTION_IN_PRIVACY_POLICY/meta.json
  MOBILE_CLIENT/COMMON/_POTENTIALLY/PRIVACY_CONTINUOUS_GPS_LOCATION_ACCESS/meta.json
  MOBILE_CLIENT/IOS/_MEDIUM/IPA_INSECURE_PRIVACY_MANIFEST_FILE/meta.json
  tests/kb_test.py
Labels: CNIL

#234 feature: non privacy issues in CNIL standards.
  MOBILE_CLIENT/ANDROID/_HARDENING/APK_LIST_NOT_USED_PERMISSIONS/meta.json
  MOBILE_CLIENT/ANDROID/_LOW/APK_TASK_HIJACKING/meta.json
  MOBILE_CLIENT/ANDROID/_LOW/APK_USES_CLEAR_TEXT_TRAFFIC/meta.json
  MOBILE_CLIENT/COMMON/_HARDENING/DEPRECATED_COMPONENT/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/BIOMETRIC_AUTHENTICATION_BYPASS/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_PASSWORD_STORAGE/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_STORAGE/meta.json
  MOBILE_CLIENT/IOS/_LOW/UNSAFE_KEYCHAIN_ACCESSIBILITY/meta.json
  MOBILE_CLIENT/IOS/_MEDIUM/IPA_INSECURE_TAP/meta.json
  MOBILE_CLIENT/IOS/_MEDIUM/IPA_URL_SCHEME_HIJACKING/meta.json
Labels: CNIL

#235 fix: improvements to CNIL standards
  MOBILE_CLIENT/ANDROID/_HARDENING/APK_INSECURE_NETWORK_SECURITY_CONFIG/meta.json
  MOBILE_CLIENT/COMMON/_HIGH/INSECURE_JWT_SIGNATURE/meta.json
  MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_CIPHER_ALGO/meta.json
  MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_CIPHER_MODE/meta.json
  MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_IV/meta.json
  MOBILE_CLIENT/COMMON/_LOW/INSECURE_RANDOM_SEED/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/CRYPTO_INSECURE_CIPHER_KEY/meta.json
  MOBILE_CLIENT/COMMON/_MEDIUM/WEAK_HASHING_ALGO/meta.json
  MOBILE_CLIENT/IOS/_MEDIUM/IPA_INSECURE_TAP/meta.json
Labels: CNIL
